[package]
name = "iron-leveldb"
authors = ["Finley Huggins"]
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
rusty-leveldb.workspace = true
flate2.workspace = true
