[package]
name = "prismarine-editor"
authors = ["Finley Huggins"]
license.workspace = true
version.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
prismarine-nbt.workspace = true

rusty-leveldb.workspace = true
flate2.workspace = true
